########################
### GENERAL SETTINGS ###
########################
set -g default-terminal "tmux-256color"
set -g default-shell /bin/zsh
set -g default-command /bin/zsh
# set -g default-command "reattach-to-user-namespace -l zsh"
set -sa terminal-overrides ",xterm*:Tc"

# enable mouse support
set -g mouse on

# copy-paste
setw -g mode-keys vi

# enable viewing images in terminal
set -gq allow-passthrough on
set -g visual-activity off

###################
### STATUS LINE ###
###################
set -g status-left-length 100
set -g status-right-length 200

# set -g @kanagawa-show-left-icon "#h | #S"
#
# set -g @kanagawa-show-left-sep 
# set -g @kanagawa-show-right-sep 
#
# set -g @kanagawa-plugins "ssh-session cpu-usage ram-usage"
# set -g @kanagawa-narrow-plugins "compact-alt cpu-usage ram-usage"
# set -g @kanagawa-show-flags true
# set -g @kanagawa-show-powerline true
# set -g @kanagawa-ignore-window-colors true
# set -g @kanagawa-show-edge-icons true

set -g @gruvbox-show-powerline true
set -g @gruvbox-show-left-sep 
set -g @gruvbox-show-left-icon session
set -g @gruvbox-left-icon-padding 1
set -g @gruvbox-show-flags true

set -g @gruvbox-show-right-sep 
set -g @gruvbox-show-ssh true
set -g @gruvbox-show-ssh-session-port false
set -g @gruvbox-show-network false
set -g @gruvbox-show-weather false
set -g @gruvbox-show-location false
set -g @gruvbox-show-time false
set -g @gruvbox-cpu-usage true
set -g @gruvbox-ram-usage true
set -g @gruvbox-gpu-usage true

set-option -g status-position top
set-option -g automatic-rename off
set-option -g allow-rename off

####################
### KEY BINDINGS ###
####################
# rebind CTRL-b to CTRL-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload tmux config file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# create a binding for creating a new session
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"

# create a binding for killing a session
bind K confirm kill-session

# rebind horizontal pane splitting
unbind %
bind | split-window -h -c "#{pane_current_path}"

# rebind vertical pane splitting
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# resize panes
bind -r j resize-pane -D 5  # resize downward
bind -r k resize-pane -U 5  # resize upward
bind -r l resize-pane -R 5  # resize rightward
bind -r h resize-pane -L 5  # resize leftward
bind -r m resize-pane -Z    # maximize pane

bind , command-prompt -I "#W" "rename-window '%%'"
bind . command-prompt "move-window -t '%%'"

#########################
### PANES AND WINDOWS ###
#########################
# renumber windows automatically
set-option -g renumber-windows on

# start window and pane indices at 1
set -g base-index 1
setw -g pane-base-index 1

###############
### PLUGINS ###
###############
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-cpu"
set -g @plugin "sainnhe/tmux-fzf"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
# set -g @plugin "Nybkox/tmux-kanagawa"
# set -g @plugin "spywhere/tmux-now-playing"
set -g @plugin "janders223/gruvbox-tmux"

set -g @resurrect-capture-pane-contents "on"
set -g @resurrect-dir "$HOME/.tmux/resurrect/"
set -g @continuum-restore "on"
set -g @continuum-save-interval "15"

# set -g @kanagawa-theme "wave"
# set -g @kanagawa-refresh-rate 1

# set -g status-right "#{now_playing}"

run "~/.tmux/plugins/tpm/tpm"
