jira_api_username: "sam@tristar.ai"
jira_api_token: "ATATT3xFfGF0YVChi1GtLqjORT47-V_WMkB2VC5w9hxM03vLjk2aVXNH3iNA9KHvje4FNKmEw9dCgnTcPOIxgQjU7w9AZUz_4pJAoFD0IqnDIWcW6Wk1J3-yfuc95WZVSX4uFTBROiZIBoonJiDLUsnyTWyNZjsn09WCwz_CrTfuNuWhokJNtTs=86F9566C"
jira_api_base_url: "https://tristar-ai.atlassian.net"
theme: "gruvbox"
